CREATE DATABASE  IF NOT EXISTS `quiz_db` /*!40100 DEFAULT CHARACTER SET latin1 */;
USE `quiz_db`;
-- MySQL dump 10.13  Distrib 5.7.17, for Win64 (x86_64)
--
-- Host: localhost    Database: quiz_db
-- ------------------------------------------------------
-- Server version	5.7.19

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

--
-- Table structure for table `answer`
--

DROP TABLE IF EXISTS `answer`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `answer` (
  `ans_id` int(11) NOT NULL AUTO_INCREMENT,
  `answer` mediumtext NOT NULL,
  `hint` mediumtext,
  PRIMARY KEY (`ans_id`),
  UNIQUE KEY `ans_id_UNIQUE` (`ans_id`)
) ENGINE=InnoDB AUTO_INCREMENT=21 DEFAULT CHARSET=latin1;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `answer`
--

LOCK TABLES `answer` WRITE;
/*!40000 ALTER TABLE `answer` DISABLE KEYS */;
INSERT INTO `answer` VALUES (1,'T',''),(2,'F',''),(3,'F',''),(4,'T',''),(5,'T',''),(6,'F',NULL),(7,'T',NULL),(8,'F',NULL),(9,'F',NULL),(10,'T',NULL),(11,'.PHP','._ h _'),(12,'Servlets','S _ r _ _ _ t s'),(13,'Instantiation','_ n _ t _ n _ _ a _ _ o n'),(14,'1994','1 9 _ _'),(15,'Personal Home Page','P _ _ _ o _ _ l  H _ m _e  P a _ _'),(16,'Rasnus Lerdorf','R _ _ n _ s  _ e r _ o _ f'),(17,'Context Listener','C _ _ t _ x _  L _ s _ _ n _ r'),(18,'Initialization','I _ i _ _ a l _ z _ _ _ o n'),(19,'end event','_ n _  e _ _ n t'),(20,'HTTP Servlet Response','H _ _ P  S _ r v _ _ t  R _ s _ _ n _ e');
/*!40000 ALTER TABLE `answer` ENABLE KEYS */;
UNLOCK TABLES;

--
-- Table structure for table `ques_ans`
--

DROP TABLE IF EXISTS `ques_ans`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `ques_ans` (
  `ques_id` int(11) NOT NULL AUTO_INCREMENT,
  `question` longtext NOT NULL,
  `ans_id` int(11) NOT NULL,
  `type` enum('tf','iden') NOT NULL,
  PRIMARY KEY (`ques_id`),
  UNIQUE KEY `ques_id_UNIQUE` (`ques_id`),
  KEY `ans_id_idx` (`ans_id`),
  CONSTRAINT `ans_id` FOREIGN KEY (`ans_id`) REFERENCES `answer` (`ans_id`) ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=21 DEFAULT CHARSET=latin1;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `ques_ans`
--

LOCK TABLES `ques_ans` WRITE;
/*!40000 ALTER TABLE `ques_ans` DISABLE KEYS */;
INSERT INTO `ques_ans` VALUES (1,'PHP is created in 1994 by Rasmus Lerdorf',1,'tf'),(2,'In PHP, to create an instance of class \"new\" keyword is not required.',2,'tf'),(3,'The first stage in java servlet life cycle is creation.',3,'tf'),(4,'Java server used to handle HTTP requests and generate HTTP responses.',4,'tf'),(5,'Java Servlet handles client requests by generating responses to such requests.',5,'tf'),(6,'In Java servlet lifecycle, initialization is invoked multiple times and is intended for any startup initialization code.',6,'tf'),(7,'PHP: Hypertext Preprocessor is a server-side scripting language designed for web development but also used as a general-purpose programming language.',7,'tf'),(8,'The last or final stage in java servlet lifecycle is deletion.',8,'tf'),(9,'In PHP, a class can be inherited from one base class and with multiple base classes.',9,'tf'),(10,'A Java servlet is a Java program that extends the capabilities of a server.',10,'tf'),(11,'Default extension of PHP',11,'iden'),(12,'Java Classes which extends \"HttpServlet\"',12,'iden'),(13,'Object of the Servlet is created',13,'iden'),(14,'Year when PHP was initially created',14,'iden'),(15,'PHP initially stood for ___',15,'iden'),(16,'He initially created and designed PHP',16,'iden'),(17,'Listens for events that happens in the context',17,'iden'),(18,'Invoked only once and is intended for any startup initialization code',18,'iden'),(19,'Entire request has been terminated',19,'iden'),(20,'Object representation of the HTTP response generated by the servlet',20,'iden');
/*!40000 ALTER TABLE `ques_ans` ENABLE KEYS */;
UNLOCK TABLES;
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

-- Dump completed on 2018-05-12  6:19:58
